### ISSUE TITLE
Complilation error

### ISSUE THREAD

**Issue by microfuge** [asl/BandageNG#110]
Hi,

Thanks for this awesome package!
The static app images provided do not work on our systems due to an old glibc. I tried compiling with gcc version 10 and Qt6, following the instructions. But I constantly get 
```
build/_deps/lexy-src/include/lexy/dsl/operator.hpp:149:86: error: could not convert ‘(& reader)->lexy::_prd::<anonymous>.lexy::_pr<lexy::default_encoding>::<anonymous>.lexy::_rr<lexy::default_encoding, const char*, const char*>::position()’ from ‘lexy::_rr<lexy::default_encoding, const char*, const char*>::iterator’ {aka ‘const char*’} to ‘lexy::_sign<-1>’
  149 |                                                           op_tag_type(reader.position()));
      |                                                                       ~~~~~~~~~~~~~~~^~
      |                                                                                      |
      |                                                                                      lexy::_rr<lexy::default_encoding, const char*, const char*>::iterator {aka const char*}

``` 
I would be super grateful for your help with this error. 
Thanks!

**Comment by asl** [comment]
Hello

This looks like a gcc problem. The releases are built with GCC 9.4.0 (on GitHub Actions) and GCC 11 also works. So, likely the only solution is to try different GCC version.

**Comment by microfuge** [comment]
Dear Anton,

Thanks so much. gcc/v9.4.0 worked perfectly and resulted in a clean compile! 

Thanks Again and the issue is fixed from my side.

**Comment by asl** [comment]
Great it worked!
