### ISSUE TITLE
Node has negative length

### ISSUE THREAD

**Issue by rlorigro** [asl/BandageNG#116]
When loading this graph:
https://rlorigro-public-files.s3.us-west-1.amazonaws.com/gfase/verkko/full_coverage/bandage_error.gfa

I get this result in the latest release of BandageNG:
![image](https://user-images.githubusercontent.com/28764332/188246194-465bfaf2-2341-456b-afb8-8324c00b8b8b.png)

It looks like this in original Bandage:
![image](https://user-images.githubusercontent.com/28764332/188246204-fb3d1904-5bfb-4517-8400-d9f24947ce23.png)

**Comment by asl** [comment]
Nice catch! Bandage legacy code uses signed integers everywhere... And this causes sometimes fun stuff like this. Will fix.

**Comment by rlorigro** [comment]
Hi, just checking in, are there plans for an October release that includes this fix? It seems to be a very persistent error in Verkko graphs

**Comment by asl** [comment]
@rlorigro Oh, sorry, yes! Was pretty busy recently... This reminds me that we'd likely simply need rolling releases :)

**Comment by rlorigro** [comment]
Ok, no problem, looking forward to switching over :+1:

**Comment by rlorigro** [comment]
just another bi-monthly check in on this..

**Comment by asl** [comment]
@rlorigro I wanted to also make windows snapshots for 2022.10 release... but probably I'd just make a snapshot soon ;)

**Comment by asl** [comment]
@rlorigro Here we go: https://github.com/asl/BandageNG/releases/tag/v2022.09
