### ISSUE TITLE
confusing 

### ISSUE THREAD

**Issue by kingforest93** [asl/BandageNG#120]
Dear Dr. Korobeynikov,

Thank you for the development of BandageNG. I am viewing the follwing Hi-C scaffolding results in GFA "Link" and GFA v1.2 "Jump" format in BandageNG. The view of GFA "Link" format is easy to understand, and a linked group of contigs corresponds to a chromosome. But the view of GFA v1.2 "Jump" is confusing, and the linked contigs seem to be randomly placed in the workplace. Could you help explain this problem? Is it due to my incorrect settings or the imperfect design of BandageNG?

GFA format:
S     chr1_1   *      LN:i:24433468
S     chr1_2   *      LN:i:5994203
S     chr5_1   *      LN:i:10643942
S     chr5_2   *      LN:i:7618754
S     chr5_3   *      LN:i:8712806
S     chr3       *      LN:i:23459830
S     chr2_1   *      LN:i:8279532
S     chr2_2   *      LN:i:11418757
S     chr4_1   *      LN:i:3274824
S     chr4_2   *      LN:i:5649457
S     chr4_3   *      LN:i:9660775
L     chr1_1   +     chr1_2   +     0M
L     chr5_1   +     chr5_2   +     0M
L     chr5_2   +     chr5_3   +     0M
L     chr2_1   +     chr2_2   +     0M
L     chr4_1   +     chr4_2   +     0M
L     chr4_2   +     chr4_3   +     0M
 
View of GFA format in BandageNG:
![5e11d0a9779529d7c75987bece5fce5](https://user-images.githubusercontent.com/41632841/196035997-da2c1a0a-f8a6-4d50-9f96-84cf15e493c5.jpg)

GFA v1.2 format:
S     chr1_1   *      LN:i:24433468
S     chr1_2   *      LN:i:5994203
S     chr5_1   *      LN:i:10643942
S     chr5_2   *      LN:i:7618754
S     chr5_3   *      LN:i:8712806
S     chr3       *      LN:i:23459830
S     chr2_1   *      LN:i:8279532
S     chr2_2   *      LN:i:11418757
S     chr4_1   *      LN:i:3274824
S     chr4_2   *      LN:i:5649457
S     chr4_3   *      LN:i:9660775
J     chr1_1   +     chr1_2   +     *      SC:i:1
J     chr5_1   +     chr5_2   +     *      SC:i:1
J     chr5_2   +     chr5_3   +     *      SC:i:1
J     chr2_1   +     chr2_2   +     *      SC:i:1
J     chr4_1   +     chr4_2   +     *      SC:i:1
J     chr4_2   +     chr4_3   +     *      SC:i:1

View of GFA v1.2 format in BandageNG:
![54b225e940c3d929826cfa56da48afc](https://user-images.githubusercontent.com/41632841/196036004-f523a565-2ded-4169-b72d-6f556b0be491.jpg)

**Comment by asl** [comment]
Jump links are not included into layout as they could "glue" all the nodes together (they often represent distant links and therefore cannot "guide" the genome).

We might make this behaviour as optional though in the future versions of BandageNG

**Comment by kingforest93** [comment]
Thank you for your quick response!
I will wait for the future version of BandageNG that can handle Jump links.


Best regards,


Sen Wang
















在 2022-10-16 20:54:46，"Anton Korobeynikov" ***@***.***> 写道：

Jump links are not included into layout as they could "glue" all the nodes together (they often represent distant links and therefore cannot "guide" the genome).

We might make this behaviour as optional though in the future versions of BandageNG

**Comment by asl** [comment]
The current version perfectly handles jump links. The decision not to introduce them into layout was made deliberately as these links in general do not provide the proper genomic order and could screw the proper layout otherwise.

**Comment by kingforest93** [comment]
Oh, I see. I make a mistake in understanding the design of Jump connections. That is to say, Jump connections should provide correct orders and orientations of contigs just like the Links do.
Actually, I'm using GFA Jump to help me view the scaffolding process with Hi-C contact data. This may be already out of the scope of Jump connections in GFA format.


Thank you so much for the patient response!
Best regards,


Sen Wang
















在 2022-10-16 21:20:42，"Anton Korobeynikov" ***@***.***> 写道：

The current version perfectly handles jump links. The decision not to introduce them into layout was made deliberately as these links in general do not provide the proper genomic order and could screw the proper layout otherwise.

**Comment by asl** [comment]
Well, in your particular case you could easily have the following:

```
J  A  + B +
J  A  + C +
J  B  + C +
```

Note that the order it correct (genomic), however if you'd add normal links here as well you could easily "glue" everything together. This is why jump links do change the segment layout. It is supposed that you do this by hands.

**Comment by kingforest93** [comment]
Thanks for your suggestion! I'll give it a try.


Best regards,


Sen Wang
















在 2022-10-16 22:22:35，"Anton Korobeynikov" ***@***.***> 写道：

Well, in your particular case you could easily have the following:

J  A  + B +
J  A  + C +
J  B  + C +


Note that the order it correct (genomic), however if you'd add normal links here as well you could easily "glue" everything together. This is why jump links do change the segment layout. It is supposed that you do this by hands.
