### ISSUE TITLE
Incorrect data loaded from CSV file

### ISSUE THREAD

**Issue by rlorigro** [asl/BandageNG#122]
The same GFA and CSV produce different results in OG vs NG Bandage:

Bandage NG
![image](https://user-images.githubusercontent.com/28764332/200202323-b8dd88ce-1d19-4e26-932a-89829e6a3f3e.png)

Original Bandage
![image](https://user-images.githubusercontent.com/28764332/200202347-770d9343-aebb-4f70-9214-360e096138f6.png)

CSV:
https://rlorigro-public-files.s3.us-west-1.amazonaws.com/gfase/test_gfa/chainable_nodes.csv

GFA:
https://rlorigro-public-files.s3.us-west-1.amazonaws.com/gfase/test_gfa/chain_test.gfa

**Comment by asl** [comment]
Ok, this is an outcome how we're matching path names in CSV. Path names are matched by prefix, so in your particular case node name `t` matched against paths `tip.0` and `tip.1`. I do not recall why we matched paths before nodes. Current workaround is to rename / remove paths.

I will revise the logic here.

**Comment by asl** [comment]
Ah, yes, I remember why we're checking paths first. Unfortunately, when exporting to FASTA Bandage exports node names in the format like `NODE_6+_length_50434_cov_42.3615` which obviously clashes with the standard naming of paths in e.g. SPAdes assembly graphs.

While querying for node name it transforms `NODE_6+_length_50434_cov_42.3615` into just `6+`. This logic obviously could transform path name into some valid node name and do some wrong things.

Probably, the only sane solution is to require explicit path name, not just prefix check.

**Comment by rlorigro** [comment]
Hey @asl could this potentially be added to a new release? Perhaps you could switch from monthly to a yearly release schedule  :)

**Comment by asl** [comment]
@rlorigro We're having rolling releases these days: https://github.com/asl/BandageNG/releases/tag/continuous

So, you could always grab the latest snapshot
