### ISSUE TITLE
coverage question

### ISSUE THREAD

**Issue by svedwards** [asl/BandageNG#132]
Hi -
I'm really enjoying Bandage-NG. We have it running on a virtual desktop on our cluster (using Singularity), so if anyone has trouble setting that up, please let me know. command: singularity exec /cvmfs/singularity.galaxyproject.org/b/a/bandage_ng:2022.09--h9f5acd7_0 Bandage

I had a question about coverage, when I output part of a graph in fasta format. Several nodes have cov_0 (see below). Does coverage mean the number of haplotypes spanning the node? And is it 0-based? Finally, is there any general documentation for the outputs? Thank you! - Scott

>NODE_67621+_length_5_cov_0
TTCCC
>NODE_67622+_length_1_cov_0
A
>NODE_67623+_length_1_cov_0
G
>NODE_67624+_length_2_cov_0
GT
>NODE_67625+_length_2_cov_0
GC
>NODE_67626+_length_2_cov_0
AT
>NODE_67627+_length_8_cov_0
TCCCAGTA

**Comment by asl** [comment]
Well, coverage is... coverage. I.e. the average number of bases spanning each position of the node. It is loaded from the input graph, so if this information is not present, then the coverage will be zero.

Bandage-NG has no idea about haplotypes, etc.

Some information about the output is available in the vanilla Bandage wiki (https://github.com/rrwick/Bandage/wiki/Output) though it might be not up to date for Bandage-NG. Patches are always welcome :)
