### ISSUE TITLE
bandage  image 

### ISSUE THREAD

**Issue by xhlin321** [asl/BandageNG#133]
Thank you for continuing to maintain the bandage. I want to ask how to draw part of the graphics after the bandage blast through the command line instead of the gui, and how to add node parameters to the graphics，for example ,when i  run " Bandage image sniffles.gfa  12.svg --query  pigh.fa  --scope aroundblast --distance 3 "  the out file is all the blast result ,but i want get only one which is the best blast rensult  like this

**Comment by xhlin321** [comment]
![Uploading CDE9082C-1857-45DF-B3E8-B42BBDE519FB.png…]()

**Comment by xhlin321** [comment]
![Uploading 3A13F00C-E2B7-47F3-9988-F1153C4F4B86.jpeg…]()

**Comment by xhlin321** [comment]
![77273674-E482-444E-B3DB-01CDF654CE3A](https://user-images.githubusercontent.com/101160438/224330974-212c8f31-73ae-433d-898f-3eab6242a14a.png)

**Comment by xhlin321** [comment]
![Uploading 17981D4D-82E2-468E-B808-186CA8BE40BB.jpeg…]()

**Comment by xhlin321** [comment]
![0B60B18F-343C-4214-960D-CCC3B786D315](https://user-images.githubusercontent.com/101160438/224331209-95d28f8d-a4b6-4726-a696-61bef40772d2.jpeg)

**Comment by asl** [comment]
Hello

There is no such functionality, because there is no way to define "best BLAST result". Likely you can narrow down your search via adding blast filters, so there will be less BLAST hits.

**Comment by xhlin321** [comment]
Thanks for u advice!But how can I How can I implement blast filtering on the command line not the GUI

**Comment by asl** [comment]
`--help` contains the following section:

```
[Option Group: BLAST search]
  Options:
    --blastp TEXT               Parameters to be used by blastn and tblastn when conducting a BLAST search in Bandage-NG.
                                Format BLAST parameters exactly as they would be used for blastn/tblastn on the command line, and enclose them in quotes.
    --alfilter INT:INT in [1 - 1000000] [off]
                                Alignment length filter for BLAST hits. Hits with shorter alignments will be excluded
    --qcfilter FLOAT:FLOAT in [0 - 100] [off]
                                Query coverage filter for BLAST hits. Hits with less coverage will be excluded
    --ifilter FLOAT:FLOAT in [0 - 100] [off]
                                Identity filter for BLAST hits. Hits with less identity will be excluded
    --evfilter SCINOT:FLOAT in [1e-999 - 99] [off]
                                E-value filter for BLAST hits. Hits with larger e-values will be excluded
    --bsfilter FLOAT:FLOAT in [0 - 1e+06] [off]
                                Bit score filter for BLAST hits. Hits with lower bit scores will be excluded
[Option Group: BLAST query paths]
  These settings control how Bandage-NG searches for query paths after conducting a BLAST search
  Options:
    --pathnodes INT:INT in [1 - 50] [6]
                                The number of allowed nodes in a BLAST query path
    --minpatcov FLOAT:FLOAT in [0.3 - 1] [0.9]
                                Minimum fraction of a BLAST query which must be covered by a query path
    --minhitcov FLOAT:FLOAT in [0.3 - 1], or "off" [0.9]
                                Minimum fraction of a BLAST query which must be covered by BLAST hits in a query path
    --minmeanid FLOAT:FLOAT in [0 - 1], or "off" [0.5]
                                Minimum mean identity of BLAST hits in a query path
    --maxevprod SCINOT:FLOAT in [1e-999 - 99], or "off" [1e-10]
                                Maximum e-value product for all BLAST hits in a query path
    --minpatlen FLOAT:FLOAT in [0 - 10000], or "off" [0.95]
                                Minimum allowed relative path length as compared to the query
    --maxpatlen FLOAT:FLOAT in [0 - 10000], or "off" [1.05]
                                Maximum allowed relative path length as compared to the query
    --minlendis INT:INT in [-1000000 - 1000000], or "off" [off]
                                Minimum allowed length discrepancy (in bases) between a BLAST query and its path in the graph
    --maxlendis INT:INT in [-1000000 - 1000000], or "off" [off]
                                Maximum allowed length discrepancy (in bases) between a BLAST query and its path in the graph
```

Hope it will help

**Comment by xhlin321** [comment]
Thank u very much for u answer! i run ' Bandage image sniffles.gfa  12.svg   --query  pb1.fa  --scope aroundblast --distance 1  --bsfilter 500' ,then i got a svg like this , i wan to get the lenths in my picture ,what  can i add some parameters  in command line ' Bandage image sniffles.gfa  12.svg   --query  pb1.fa  --scope aroundblast --distance 1  --bsfilter 500'(because my gui cannot work)

**Comment by xhlin321** [comment]
![Uploading 5B4ACFAC-79C1-4EF0-A1F1-746DAD84841C.png…]()

**Comment by xhlin321** [comment]
this is my want in the end
![Uploading FF9E70A1-D069-4F5D-80AE-AF3F7F130AF1.png…]()

**Comment by xhlin321** [comment]
![269C2BEF-8366-4C9F-9E7F-BF952FF62441](https://user-images.githubusercontent.com/101160438/224470358-634c1b87-a6d0-49d6-aac8-7084ce85cfa7.png)

**Comment by xhlin321** [comment]
and this is what I want in the end 
![7D786970-68ED-4A35-8DD4-997E09BB1220](https://user-images.githubusercontent.com/101160438/224470393-fd1b6cbe-31c5-49fd-b872-a94d470f00f7.png)

**Comment by asl** [comment]
Let us look into `--help` together again:

```
[Option Group: Node labels]
  Options:
    --csv TEXT:FILE             A CSV file with additional info
    --names                     Label nodes with name
    --lengths                   Label nodes with length
    --depth                     Label nodes with depth
    --blasthits                 Label BLAST hits
    --fontsize INT:INT in [1 - 100] [-1]
                                Font size for node labels
```

**Comment by asl** [comment]
Please reopen if there are still issues
