### ISSUE TITLE
Self-loop not drawn

### ISSUE THREAD

**Issue by maickrau** [asl/BandageNG#134]
In the linux version of release v2022.09, the edge of a node looping on itself is not drawn. Here is a graph to reproduce:

```
S    1    A
L    1    +    1    +    0M
```

This is how bandage displays the graph:

![Screenshot from 2023-06-12 14-19-26](https://github.com/asl/BandageNG/assets/1543674/f2fbbafd-8f72-46d7-90d9-dd44608a28f9)

The graph information correctly counts the edge, but it is not drawn.

**Comment by asl** [comment]
@maickrau This will be a part of rolling release as soon as snapshots will be built: https://github.com/asl/BandageNG/releases/tag/continuous
