### ISSUE TITLE
Support for nodes larger than 2^27

### ISSUE THREAD

**Issue by diego-rt** [asl/BandageNG#143]
Hello,

I'm trying to visualise an assembly of a 30+ Gbp genome and some of the nodes are more than a few hundred megabases. I've realised that nodes larger than 134217728 bp are not processes by BandageNG and neither visualised or included in the statistics under graph information. Is there are chance assemblies with nodes of this size can be supported in the future? 

Thanks!!

**Comment by asl** [comment]
Are you sure you're using the latest version? We do support nodes up to ~1 Gbp (30 bits).

**Comment by diego-rt** [comment]
As far as I can tell, I am using v2022.09. Or should I try the continuous build?

**Comment by asl** [comment]
This is very old version. We are using rolling releases since then. The particular change was implemented ~year ago

**Comment by diego-rt** [comment]
Oh I see! Ok, I will give it a try. And what if my contigs ever surpass the 1 Gb mark? Our chromosomes are 1.5-4 Gb and we are aiming for T2T. I guess that would be difficult to implement?

**Comment by diego-rt** [comment]
Apologies, you are totally right. It works with the continuous build for macOS.

**Comment by asl** [comment]
> Oh I see! Ok, I will give it a try. And what if my contigs ever surpass the 1 Gb mark? Our chromosomes are 1.5-4 Gb and we are aiming for T2T. I guess that would be difficult to implement?

This is not something we're going to handle as it would increase memory consumption for all users drastically.
