### ISSUE TITLE
Bandage-NG on Windows?

### ISSUE THREAD

**Issue by Ecoulembier** [asl/BandageNG#151]
Would Bandage-NG be released on windows? Finding Paths specifically would be incredibly useful which I cannot do in Bandage.

**Comment by asl** [comment]
Duplicate of #31 

See https://github.com/asl/BandageNG/issues/31#issuecomment-2250736527

**Comment by asl** [comment]
@Ecoulembier can you try downloading artifacts from https://github.com/asl/BandageNG/actions/runs/10119374072 and see if it works for you?

**Comment by Ecoulembier** [comment]
It works for me, thanks for putting in the effort!
