### ISSUE TITLE
Paths not found in bandageNG

### ISSUE THREAD

**Issue by Ecoulembier** [asl/BandageNG#159]
I have a .gfa file with added P-lines, but once uploaded in BandageNG the path Length is considered '0'. I checked the input file and there are actually complete paths in the file for all the input assemblies. Is there another way to add the Paths to BandageNG?

**Comment by asl** [comment]
Likely your GFA has wrong format. We do not have good ways to diagnose this currently (though this is planned). Please attach the corresponding GFA, so I can take a look

**Comment by Ecoulembier** [comment]
Hi,

 

Here is the GFA I used: https://we.tl/t-nvdDay8FR0

 

Thanks in advance!

**Comment by asl** [comment]
The current version of Bandage-NG shows the following error message:
```
malformed path string for path 'SLF', cannot reconstruct the path through the graph
```

I went ahead and improved the error reporting further, so it now also shows: "no path between nodes s778+  => s780+".

And indeed, `s778` is a deadend:
<img width="786" alt="Screenshot 2024-09-04 at 12 23 30" src="https://github.com/user-attachments/assets/ad0d7a19-e989-4ca7-8f98-f780520720f0">
