### ISSUE TITLE
Invalid path missing segment orientation causes crash upon loading graph

### ISSUE THREAD

**Issue by ASLeonard** [asl/BandageNG#166]
In the case of a malformed path in the gfa, specifically a segment missing its orientation, BandageNG will just instantly crash and exit (at least on macos). 

This graph is able to reproduce the behaviour (or the path segment `1,2+`). Changing to the valid `1+,2+` will load the graph successfully)
```
S       1       TAG
S       2       CAT
L       1       +       2       +       0M
P       foo     1+,2    0M
```

It seems like *oriented_segment* in io/gfa.cpp should handle invalid input and complain later, but this just crashes.

Best,
Alex

**Comment by asl** [comment]
Thanks for the report! Apparently, it seems that while there is a note in `oriented_segment` that segment name should be validated further on, this did not happen.

Should be fixed in #167 (and new snapshot will be available shortly)
