### ISSUE TITLE
QT6 issue

### ISSUE THREAD

**Issue by AdamVS** [asl/BandageNG#168]
Hi there - I probably have developed a bug or broken some dependency which affects Bandage-NG (in a mamba/conda environment) and also Bandage-NG from https://github.com/ctlab/BandageNG. I'm running those in Ubuntu 22.04 and they were functioning normally until recently.

Upon starting Bandage-NG I have the error:

`Bandage: symbol lookup error: Bandage: undefined symbol: _ZN9QMetaType14registerHelperEPKN9QtPrivate18QMetaTypeInterfaceE, version Qt_6
`

The Qt6 packages in the Bandage-NG environment are:
```
# Name                    Version                   Build  Channel
bandage_ng                2022.09              h4ac6f70_2    bioconda
qt6-main                  6.4.2                ha893420_4    conda-forge
```

An older version of Bandage from rrwick (https://github.com/rrwick/Bandage) works with the following Qt5 packages:
```
# Name                    Version                   Build  Channel
bandage                   0.8.1                hc9558a2_2    bioconda
qt                        5.15.6               hf11cfaa_0    conda-forge
qt-main                   5.15.6               h602db52_6    conda-forge
qt-webengine              5.15.4               h325cec9_3    conda-forge
```

any pointers? 

cheers and thanks

**Comment by asl** [comment]
Hello

It seems you're referring to a very old release and a fork I have not connection with.

Does the problem reproduce with the latest release from https://github.com/asl/BandageNG/releases/tag/continuous?

**Comment by AdamVS** [comment]
Hi thanks for the info - I have quickly tested this appimage (on the same system), and while the data appears to load, it crashes upon draw graph. When I have time I will try the latest source. I will also try to test on various other machines and note the qt6 version.

**Comment by asl** [comment]
> and while the data appears to load, it crashes upon draw graph.

This might be a different issue then. Will you please upload the graph, so I can check?

**Comment by AdamVS** [comment]
Hi Anton - it continues to be an issue with multiple graphs and for graphs which have been been opened before - so I suspect it is an issue with qt6(?) in selected workstations - I am in the process of checking that, and will have more info tomorrow. As mentioned above, Bandage (from rrwick), continues to work with these graphs.

**Comment by AdamVS** [comment]
It looks like this is tied to a specific workstation, so for the time being you can close this issue. Thank you!!
