### ISSUE TITLE
walk lines gfa from cactus-pangenome

### ISSUE THREAD

**Issue by alpapan** [asl/BandageNG#169]
Currently i can't get bandage-ng to recognise the walk lines produced by cactus pangenome

they include the [haplotype number](https://gfa-spec.github.io/GFA-spec/GFA1.html#required-fields-6).
Bandage gives an error when trying to import it.
```
W	MDB2_Nov24	2	h2tg000001l	0	48685588	<11603.....
```

If i remove the third column then the file is read without issues.
for example removing the third column 2 here allows bandage-ng to read the file without an error but the walk lines are not really parsed/available under More Info->Walks

am i doing something wrong?

**Comment by alpapan** [comment]
possibly related to this [commit](https://github.com/asl/BandageNG/pull/153)?

**Comment by asl** [comment]
Will you please attach an example graph?

**Comment by alpapan** [comment]
i think i found the issue, [it's what you found last time](https://github.com/asl/BandageNG/issues/150#issuecomment-1950941617), W lines appearing before L... testing to see what happens when i move them

**Comment by alpapan** [comment]
yeap that's it!
just needed to move the walk lines at end of file!

**Comment by asl** [comment]
Yes, a valid walk must exist in the graph. So `W` before `L` is the violation of the spec and it is not valid GFA. The producer should be fixed not to produce such file. You might want to report to them
