### ISSUE TITLE
Add Mac / Windows runners

### ISSUE THREAD

**Issue by asl** [asl/BandageNG#31]
So we can ensure build is not broken there

**Comment by asl** [comment]
Some inspiration could be obtained from: https://github.com/pbek/QOwnNotes/blob/develop/.github/workflows/build-release.yml

**Comment by asl** [comment]
Mac runner added in https://github.com/asl/Bandage/commit/491b8c50432a3b8c67f1cceaf63507b577f550ba

**Comment by asl** [comment]
Runners are used to build releases. Windows runner is really needed!

**Comment by ASLeonard** [comment]
It seems there are now [windows runners](https://github.com/actions/runner-images?tab=readme-ov-file#available-images). Is this something we can work on (I have no windows experience but happy to try and help)? 

I was teaching a pangenome workshop recently and all the windows-users were able to use `Bandage` but not `BandageNG` and the new improvements like path loading and BED annotations are infinitely valuable.

**Comment by asl** [comment]
> I was teaching a pangenome workshop recently and all the windows-users were able to use `Bandage` but not `BandageNG` and the new improvements like path loading and BED annotations are infinitely valuable.

Last time I tried to make Windows port I saw some visual issues that are clearly were Qt bugs (as they were absent on Linux / Windows). I did not have time to find a workaround (I spend maybe few hours to no avail) so I left it as-is. Maybe I will just provide a port and let someone else to deal with these issues ;)

**Comment by asl** [comment]
@ASLeonard can you try downloading artifacts from https://github.com/asl/BandageNG/actions/runs/10119374072 and see if it works for you?

**Comment by ASLeonard** [comment]
So it works for @Ecoulembier as reported (on windows 11) and @denisemartini (on windows 11) but crashes immediately upon laying out the graph for @RenscoHogers (on windows 10). It did work for another windows 10 user however, so maybe it was an old laptop. Many other features work like the detailed stats after loading the graph, so it seem localised to layout. 

Thanks so much for the quick help!

**Comment by asl** [comment]
> but crashes immediately upon laying out the graph for @RenscoHogers (on windows 10

I'd suspect the ogdf library uses some instructions that are not available there (e.g. SSE4). And there is no runtime detection of available instruction set.

**Comment by RenscoHogers** [comment]
Hi Anton, thank you so much for your work on making it Windows compatible. Do you know if there is there a way to check whether it is crashing due to an instruction set missing, or whether it is crashing due to another issue?

**Comment by asl** [comment]
> Hi Anton, thank you so much for your work on making it Windows compatible. Do you know if there is there a way to check whether it is crashing due to an instruction set missing, or whether it is crashing due to another issue?

The one way I am aware of is to attach a debugger and see where it is crashing...

**Comment by RenscoHogers** [comment]
Thanks for the suggestion, I figured out that the issue was likely caused by a faulty Microsoft Visual C++ Redistributable package installation. Reinstallation seems to have fixed the issue, thanks for the help!

**Comment by asl** [comment]
We are doing both Mac & Windows snapshots
