### ISSUE TITLE
Allow loading GFA files with mixed Segment/Link lines

### ISSUE THREAD

**Issue by AndreaGuarracino** [asl/BandageNG#40]
Hi,

I have multiple GFA files where the S/L lines are mixed. For example:

```
H	VN:Z:1.0
S	1	GCGGTTCAGCAATTTCAGG
L	1	+	2	+	0M
L	1	+	3	+	0M
S	2	G
L	2	+	4	+	0M
S	3	C
L	3	+	4	+	0M
...
```

In order to open them with the new power-upped Bandage, I have to put all S lines first, then L lines, and then P lines. Else, I get this kind of error:

![image](https://user-images.githubusercontent.com/62253982/171642369-002d4976-34d9-4416-8a51-d822286a15b2.png)

Is it possible to avoid such a constraint? The old Bandage can read S/L-mixed GFA files.

**Comment by asl** [comment]
This will be clarified in the next GFA spec. Essentially here you're referring to the entity (segment) that was not defined yet. We will provide some kind of workaround for these issues. For now you'd just `sort` the file using the record type as a key, so all `S` would come before `L`

**Comment by asl** [comment]
Fix included in https://github.com/asl/Bandage/releases/tag/v0.9.5.1
