### ISSUE TITLE
Cannot load a file containing segments without sequence

### ISSUE THREAD

**Issue by paoloczi** [asl/BandageNG#45]
If I try to load a gfa file containing no sequence, I get the following error message:

![image](https://user-images.githubusercontent.com/25391437/171702210-56a1b95b-879e-4800-bbf3-ffdbb8574509.png)

Here is the beginning of the file I am trying to load: 

```
H       VN:Z:1.0
S       0       *
S       1       *
S       2       *
S       3       *
```

According to the [GFA specification](https://gfa-spec.github.io/GFA-spec/GFA1.html), the sequence can be omitted and specified as `*`. The specification also says that, if the sequence is missing, "_its length may be specified using the LN tag_", but this is not required. The `LN` field is clearly described as optional, and the original Bandage has no problem loading this file.

GFA files without sequence are very useful to inspect an assembly without having to load a large file. This is useful for applications where the sequence is not needed, and one is interested only in the structure of the assembly graph.

**Comment by asl** [comment]
Dup of https://github.com/asl/Bandage/issues/43

**Comment by asl** [comment]
Fix included in https://github.com/asl/Bandage/releases/tag/v0.9.5.1
