### ISSUE TITLE
Hanging on graph load

### ISSUE THREAD

**Issue by rlorigro** [asl/BandageNG#46]
Hi, I downloaded your AppImage release v0.9.5 and tried loading a human assembly graph generated by verkko (the current state of the art for contiguity/completeness) and it created this malformed UI element and has been running like this for about 10min without finishing

![image](https://user-images.githubusercontent.com/28764332/171703275-c3b39663-ef61-435c-a33c-7f8dd216dfab.png)

The static executable from conventional bandage has successfully loaded this graph in a minute or so.

**Comment by asl** [comment]
Can you provide the input file? Likely GFA parser complains and this is why it is slow (currently we do not have good way to show these errors yet)

**Comment by rlorigro** [comment]
I have an update: the htop output for the app looks like this:
![image](https://user-images.githubusercontent.com/28764332/171704127-22fb9a13-f695-40bc-b5dc-de90e9f2b6ce.png)
And the ui element has fixed itself:
![image](https://user-images.githubusercontent.com/28764332/171704477-b0fb8f21-1f02-46a9-a99b-ed79614e557b.png)

It's been running with full CPU for about 25min

**Comment by rlorigro** [comment]
I'm not sure if I can share it. I'll ask the creators.

**Comment by asl** [comment]
You can just email me privately :)

**Comment by asl** [comment]
n/m I managed to find this file elsewhere ;)

**Comment by asl** [comment]
The current workaround is to replace "utig-" with "utig_" until we will implement some tweaks in the GFA parser

**Comment by asl** [comment]
Fix included in https://github.com/asl/Bandage/releases/tag/v0.9.5.1
