### ISSUE TITLE
Blast parameters lead to invalid arg name error

### ISSUE THREAD

**Issue by ASLeonard** [asl/BandageNG#51]
I seem to get errors setting blastn parameters (and I tried many) on the current version (v0.9.5.1) on the mac binary, that claim the arg name is invalid. It seems to strip the leading '-'

```
Error: Invalid argument name: task blastn-short -word_size 4
Error:  (CArgException::eInvalidArg) Invalid argument name: task blastn-short -word_size 4
```

Passing with `--task`, `\-task`, or `"-task "` all lead to either invalid names or positional arg errors.

Trying the same files and blast params works fine on normal Bandage, so seems to be an error in BandageNG.

**Comment by asl** [comment]
@ASLeonard Will you please provide the full cmdline? Including the way how you're running the binary?

**Comment by asl** [comment]
N/m I managed to reproduce the issue. Seems to be a fallout from Qt6 migration not covered by tests :(
