### ISSUE TITLE
Nice to have: Calculate and color nodes by GC percentage

### ISSUE THREAD

**Issue by mjpdejong** [asl/BandageNG#52]
Quickly spot contamination..

**Comment by asl** [comment]
Spoiler!

<img width="1577" alt="Screenshot 2022-06-12 at 18 28 31" src="https://user-images.githubusercontent.com/67392/173243201-f7dd96c4-ce89-431f-8192-f914f002fe20.png">

**Comment by asl** [comment]
Fixed by #59
