### ISSUE TITLE
Question about Qt prerequisite

### ISSUE THREAD

**Issue by rsharris** [asl/BandageNG#64]
This is more of a FAQ item than an issue.

The front page README lists "Qt" as a prerequisite. Is this that "Qt", or is there something else called "Qt": https://www.qt.io ?

**Comment by asl** [comment]
It's indeed "The Qt" :) Bandage-NG relies on Qt 6 for GUI

**Comment by rsharris** [comment]
Understood, thanks. Qt appears to cost ≈$300 per month, so I wanted to be sure that was the right thing before I started to consider whether I wanted to buy it.

Feel free to close this issue.

**Comment by asl** [comment]
Qt is free for open source projects. And Bandage-NG is certainly open source under GPLv3 license. See https://www.qt.io/licensing/open-source-lgpl-obligations and https://www.qt.io/download-open-source for more information

**Comment by rsharris** [comment]
Ahhh.  That's good.

Might be worth adding that as a note to the prerequisites.

Glad I asked the question!

**Comment by asl** [comment]
Well, pre-built binaries already include Qt. So there is nothing to worry about :) So, one needs Qt only for development.

**Comment by rsharris** [comment]
Not knowing anything about Qt, it wasn't clear to me whether it was something that would be part of a binary as opposed to something linked to or called from the binary.

So maybe add something like this to the prerequisites: "Qt 6. This is needed only for development, and is free for open source projects. Qt is already contained in the pre-built binaries."

Thanks in any case.  And I enjoyed your presentation to the VGP group this morning.

**Comment by asl** [comment]
Clarified in README here: https://github.com/asl/BandageNG/commit/f0a0b6acb49870493dc783c6699bc1e10a1fb7dc

Thanks!
