### ISSUE TITLE
Can't load pggb output?

### ISSUE THREAD

**Issue by yuliamostovoy** [asl/BandageNG#90]
I'm trying to load the HPRC PGGB-generated GFAs from here: https://s3-us-west-2.amazonaws.com/human-pangenomics/index.html?prefix=pangenomes/freeze/freeze1/pggb/chroms/

I get this error message:
```
There was an error when attempting to load:
/Users/ymm14/work/graphs/chr1.hprc-v1.0-pggb.nopaths.gfa

Please verify that this file has the correct format.
```

Original Bandage is able to load the same files with no issues. I'd appreciate any help, thanks!

**Comment by asl** [comment]
The graph uses "DP" tag of unexpected type. It is expected that the tag should use a floating point, not integer:

```
DP:i:1  RC:i:317470
```

We will introduce workaround in the next Bandage-NG version. For now the workaround is to replace `DP:i:` in the file with `DP:f:`.

**Comment by yuliamostovoy** [comment]
Thank you!

**Comment by paoloczi** [comment]
Actually, the [samtools specification](https://samtools.github.io/hts-specs/VCFv4.1.pdf) states in section 1.4.2 that the `DP` tag should be an integer. So the HPRC PGGB output is correct, and Bandage should expect an integer by default - although you could allow it to also accept a floating point number.

> DP : read depth at this position for this sample (Integer)

**Comment by asl** [comment]
@paoloczi The interpretation is completely different and I doubt samtools spec is irrelevant here. `DP` in case of graphs is an average depth of the node (e.g. average number of kmers / reads / fragments covered each position of the node), therefore it is expected to be a floating point value, there is no "position" here. And this is what do assemblers produce.

**Comment by paoloczi** [comment]
That is what I was thinking too before I saw that quote, and in fact I was looking for corroboration of the Bandage assumption that it is supposed to be a float. But I was not able to find any document or specification describing a floating point `DP` tag in any context - do you know of one?

**Comment by asl** [comment]
No. This is exactly what https://github.com/asl/BandageNG/issues/35 supposed to be

**Comment by asl** [comment]
@yuliamostovoy The fix is included in the following snapshot: https://github.com/asl/BandageNG/releases/tag/v2022.07.16
