### ISSUE TITLE
Strange layout of components

### ISSUE THREAD

**Issue by asl** [asl/BandageNG#93]
Hmm ok. Well this has for some reason put every component in one row, which doesn't seem very space efficient
![image](https://user-images.githubusercontent.com/28764332/179323057-eaecb73d-7bad-4a36-8b13-a149162a625f.png)

Compare this to the original packing method:
![image](https://user-images.githubusercontent.com/28764332/179323283-7a4c86fe-a73f-479f-9483-cb48e6ac452e.png)

_Originally posted by @rlorigro in https://github.com/asl/BandageNG/issues/91#issuecomment-1186017036_

**Comment by asl** [comment]
Ok, apparently the shiny new TileToRowCCPacker from OGDF was doing some strange things in some cases. So, I went ahead and ported old "embedded" packer which seems to work better and has some useful features.

I'm having the following packing of components which look reasonable to me given the aspect ratio

<img width="1208" alt="Screenshot 2022-07-17 at 23 58 39" src="https://user-images.githubusercontent.com/67392/179426377-720f3b56-a31c-4eef-9212-31dc3dfddaab.png">

**Comment by rlorigro** [comment]
That looks reasonable to me as well. The old version used to sort them by size, which was nice in some ways, but I don't have a strong preference.

**Comment by asl** [comment]
> That looks reasonable to me as well. The old version used to sort them by size, which was nice in some ways, but I don't have a strong preference.

This *is* the old version :) Note that the layout depends on aspect ratio. Essentially it tries to organize components in row-column fashion trying to preserve the aspect ratio. The algorithm is greedy: it tries to place the new component in any empty spot in every "row". And if there is no space – new row is added. As a result, if we're having one large (and wide) component, then everything got organized by size with the default square aspect ratio.

For the record, here is the layout with square scene (upper one was more rectangular):
<img width="937" alt="Screenshot 2022-07-18 at 00 23 49" src="https://user-images.githubusercontent.com/67392/179427091-1cc6eca0-40ae-4ee2-815e-5105228ca4c5.png">

**Comment by rlorigro** [comment]
Oh ok interesting. I didn't expect aspect ratio to make all the difference. I assumed the threading is what reordered things. Thanks

**Comment by asl** [comment]
Oh, no. The components are always processed being sorted by height (and first optionally rotated to be more "horizontal"). So, yes, sometimes small components could fit into spare spot
